config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'recipes/index'
  root to: "recipes#index"
  resources :recipes
  resources :users
end

app/models/allergy.rb
class Allergy < ActiveHash::Base
  self.data = [
    { id: 1,  allergy: '---' },
    { id: 2,  allergy: 'かに' },
    { id: 3,  allergy: 'えび' },
    { id: 4,  allergy: '落花生' },
    { id: 5,  allergy: 'そば' },
    { id: 6,  allergy: '小麦' },
    { id: 7,  allergy: '牛乳' },
    { id: 8,  allergy: '卵' },
    { id: 9,  allergy: '鶏肉' },
    { id: 10, allergy: '豚肉' },
    { id: 11, allergy: '牛肉' },
    { id: 12, allergy: 'ゼラチン' },
    { id: 13, allergy: 'サケ' },
    { id: 14, allergy: 'サバ' },
    { id: 15, allergy: 'いか' },
    { id: 16, allergy: 'イクラ' },
    { id: 17, allergy: '甲殻類' },
    { id: 18, allergy: '魚介類' },
    { id: 19, allergy: 'りんご' },
    { id: 20, allergy: 'オレンジ' },
    { id: 21, allergy: 'もも' },
    { id: 22, allergy: 'キウイ' },
    { id: 23, allergy: 'バナナ' },
    { id: 24, allergy: '山芋' },
    { id: 25, allergy: '松茸' },
    { id: 26, allergy: 'くるみ' },
    { id: 27, allergy: 'ごま' },
    { id: 28, allergy: 'カシューナッツ' },
    { id: 29, allergy: '大豆' }
  ]

  include ActiveHash::Associations
  has_many :recipes

  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/freezable.rb
class Freezable < ActiveHash::Base
  self.data = [
    { id: 1,  freezable: '---' },
    { id: 2,  freezable: '冷凍保存OK!' },
    { id: 3,  freezable: '冷凍保存NG.' }
  ]

  include ActiveHash::Associations
  has_many :recipes

  end

app/models/recipe.rb
class Recipe < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions



  has_one_attached :image
  belongs_to :user
  belongs_to :allergy
  belongs_to :freezable

  validates :title,           presence: true
  # validates :photo_cooking,   presence: true
  validates :allergy_id,      presence: true, numericality: { other_than: 1 , message: "can't be blank"}
  validates :cooking_time,    presence: true
  validates :ingredients,     presence: true
  validates :procedure,       presence: true
  validates :shelf_life,      presence: true
  validates :freezable_id,    presence: true, numericality: { other_than: 1 , message: "can't be blank"}
  validates :word,            presence: true
  validates :image,           presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :nickname, presence: true

  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'basket' && password == '0525'
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    # binding.pry
    if @recipe.save
      # redirect_to root_path
      redirect_to recipe_path
    else
      render :new
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def destroy
    if @recipe && @recipe.user_id == current_user.id
      @recipe.destroy
    end
  
    redirect_to root_path
  end


  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:title, :allergy_id, :ingredients, :procedure, :shelf_life, :freezable_id, :word, :image, :cooking_time).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Allergy Baby Avenger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  </head>

  <body>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

    <header>
    </header>
    <%= yield %>
    <footer>
    </footer>
  </body>
</html>

app/views/recipes/_main_chat.html.erb
<div class="chat-header">

  <p class="title">Allergy Baby Avenger</p>
  <%= image_tag "kids_eat.png", class: "recipe-image-title" %>
  <div class="header-bar-top">
    <% if user_signed_in? %>
          <%= link_to new_recipe_path(current_user), class: "btn_11" do %>
            レシピ投稿
          <% end %>
          <%= link_to destroy_user_session_path, method: :delete, class: "logout" do %>
            <button type="button" class="btn btn-outline-danger">ログアウト</button>
          <% end %>
          <div class="nickname">
            <%= link_to edit_user_path(current_user) do %>
              <button type="button" class="btn btn-outline-warning" style="font-size: 19px; padding: 5px 30px 5px 30px;"><%= current_user.nickname %></button>
            <% end %>
          </div>
    <% end %>
  </div>
</div>





<div class="messages">
    <%= image_tag "baby-food.jpg", class: "baby-food" %>
</div>



<div class="form-show">

  <div class='item-contents'>
    <div class="subtitle" >
    </div>
    <ul class='item-lists'>
        <% @recipes.each do |recipe|%>
          <li class='list'>
            <%= link_to recipe_path(recipe.id) do %>
              <div class='item-img-content'>
                <%= image_tag recipe.image.variant(resize: '200x200'), class: "item-img" if recipe.image.attached? %>
              </div>
              <div class='item-info'>
                <h3 class='item-name'>
                  <%= recipe.title %>
                </h3>
                <div class='item-price'>
                  <span><%= recipe.allergy.allergy %></span>
                  <div class='star-btn'>
                    <%= image_tag "star.png", class:"star-icon" %>
                    <span class='star-count'>0</span>
                  </div>
                </div>
              </div>
            <% end %>
          </li>
        <% end %>
    </ul>
  </div>

  <div class="footer-mozi">
    <div class="concept">～ concept  </div>
    <div class="hero">Tiny Tastemakers Unleashed ！ </div>
    <div class="mozi"> . 2023 ～</div>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="wrapper">
  <div class="chat">
    <%= render "main_chat" %>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%# <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %> 

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">～Cooking Chronicles～</h2>
    <div class="items-sell-form">
      <%= form_with(model: @recipe, url: recipes_path, multipart: true) do |f| %>

      <%# <%= render partial: 'shared/error_recipes', locals: { model: f.object } %>


      <%# # レシピ名 %>
      <div class="new-items">
          <div class="weight-bold-text">
            レシピ名
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :title, class:"recipe-title", id:"recipe-name", placeholder:"レシピのタイトル", maxlength:"50" %>
      </div>

        <%# レシピの画像 %>
        <div class="new-items-one">
            <div class="weight-bold-text">
            レシピの画像
            <span class="indispensable">必須</span>
              <div class="form-group">
                <label class="text-secondary"></label><br>
                <%= f.file_field :image %>
              </div>
              <div id="new-image"></div>
          </div>


          <%# レシピの詳細 %>
          <div class="items-detail">
            <div class="form">
              <div class="items-sell-form">
                <%# アレルギー %>
                <div class="new-items-two">
                  <div class="weight-bold-text">
                    アレルギー
                    <span class="indispensable">必須</span>
                  </div>
                  <%= f.collection_select(:allergy_id, Allergy.all, :id, :allergy, {}, {class:"select-box", id:"item-category"}) %>
                </div>
                <%# 調理時間 %>
                <div class="new-items">
                  <div class="weight-bold-text">
                    調理時間
                    <span class="indispensable">必須</span>
                  </div>
                  <%= f.text_area :cooking_time, class:"items-text-two", id:"recipe-name", placeholder:"調理時間" %>
                </div>
                <%# 材料 %>
                <div class="new-items">
                  <div class="items-explain">
                    <div class="weight-bold-text">
                      材料
                      <span class="indispensable">必須</span>
                    </div>
                  </div>
                  <%= f.text_area :ingredients, class:"items-text", id:"recipe-info", placeholder:"材料",rows:"7" ,maxlength:"5000" %>
                </div>
                <%# 調理の手順 %>
                <div class="new-items">
                  <div class="items-explain">
                    <div class="weight-bold-text">
                      調理の手順
                      <span class="indispensable">必須</span>
                    </div>
                  </div>
                  <%= f.text_area :procedure, class:"items-text", id:"recipe-info", placeholder:"調理の手順" ,rows:"7" ,maxlength:"5000" %>
                </div>
                <%# 日持ち %>
                <div class="new-items">
                  <div class="weight-bold-text">
                    日持ち
                    <span class="indispensable">必須</span>
                  </div>
                  <%= f.text_area :shelf_life, class:"items-text-two", id:"recipe-name", placeholder:"日持ち" %>
                </div>
                <%# 冷凍保存 %>
                <div class="new-items-two">
                  <div class="weight-bold-text">
                    冷凍保存
                    <span class="indispensable">必須</span>
                  </div>
                  <%= f.collection_select(:freezable_id, Freezable.all, :id, :freezable, {}, {class:"select-box", id:"item-category"}) %>
                </div>
                <%# 一言 %>
                <div class="new-items">
                  <div class="items-explain">
                    <div class="weight-bold-text">
                      一言
                      <span class="indispensable">必須</span>
                    </div>
                    <%= f.text_area :word, class:"items-text", id:"recipe-info", placeholder:"一言（500文字まで）" ,rows:"7" ,maxlength:"500" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
    </div>

    <div class="items-sell-buttons">
      <div class="sell-btn-contents">
        <%= f.submit "投稿する", class:"sell-btn" %>
        <%=link_to 'もどる', root_path, class:"back-btn" %>
      </div>
    </div>

  </div>
  <% end %>

  <footer class="items-sell-footer">

    <p class="inc">
      © Allergy Baby Avenger
    </p>
  </footer>
</div>

app/views/recipes/show.html.erb
<%# レシピの概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @recipe.title %>
    </h2>
    <div class="item-img-content">
      <%= image_tag @recipe.image.variant(resize: '500x500'), class:"item-box-img" %>
    </div>

      <% if current_user.id == @recipe.user_id %>
        <%= link_to "レシピの編集", new_recipe_path(@recipe), method: :get, class: "item-red-btn" %>
        <%=link_to 'もどる', root_path, class:"back-btn" %>
        <p class="or-text">or</p>
        <%= link_to "削除", recipe_path(@recipe), method: :delete, class:"item-destroy" %>
      <% end %>

    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">アレルギー</th>
          <td class="detail-value"><%= @recipe.allergy.allergy %></td>
        </tr>
        <tr>
          <th class="detail-item">調理時間</th>
          <td class="detail-value"><%= @recipe.cooking_time %></td>
        </tr>
        <tr>
          <th class="detail-item">材料</th>
          <td class="detail-value"><%= @recipe.ingredients %></td>
        </tr>
        <tr>
          <th class="detail-item">調理の手順</th>
          <td class="detail-value"><%= @recipe.procedure %></td>
        </tr>
        <tr>
          <th class="detail-item">日持ち</th>
          <td class="detail-value"><%= @recipe.shelf_life %></td>
        </tr>
        <tr>
          <th class="detail-item">冷凍保存</th>
          <td class="detail-value"><%= @recipe.freezable.freezable %></td>
        </tr>
        <tr>
          <th class="detail-item">一言</th>
          <td class="detail-value"><%= @recipe.word %></td>
        </tr>
      </tbody>
    </table>
    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り 0</span>
      </div>
    </div>
  </div>
  <%# /商品の概要 %>

  <div class="comment-box">
    <form>
      <textarea class="comment-text"></textarea>
      <button type="submit" class="comment-btn">
        <span>コメントする<span>
      </button>
    </form>
  </div>
</div>

app/views/users/edit.html.erb
<head>
    <meta charset="UTF-8">
    <title>Animated UPDATE Form</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
  <div class="box">
    <%= form_with model: current_user, local: true do |f| %>
      <h1>アカウント</h1>
      <h2>編集</h2>
      <h1 class=border-line>-------------</h1>
      <%= f.label :・nickname・ %>
      <%= f.text_field :nickname, autofocus: true %>
      <%= f.label :・email・ %>
      <%= f.email_field :email %>
        <%= f.submit "Update", class: 'btn btn-outline-info' %>
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'btn btn-danger', style: "margin: 20px 0 20px 0;" %>
        <%= link_to :back, class: 'btn btn-warning' do %>
          トップページに戻る
        <% end %>
    <% end %>
  </div>
</body>